# Generated by Django 5.1.7 on 2025-04-13 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkPacket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('src_ip', models.GenericIPAddressField()),
                ('dst_ip', models.GenericIPAddressField()),
                ('destination_port', models.IntegerField()),
                ('total_fwd_packets_length', models.FloatField(default=0)),
                ('total_bwd_packets_length', models.FloatField(default=0)),
                ('syn_flag_count', models.IntegerField(default=0)),
                ('ack_flag_count', models.IntegerField(default=0)),
                ('psh_flag_count', models.IntegerField(default=0)),
                ('urg_flag_count', models.IntegerField(default=0)),
                ('fwd_packet_length_mean', models.FloatField(default=0)),
                ('bwd_packet_length_mean', models.FloatField(default=0)),
                ('packet_length_mean', models.FloatField(default=0)),
                ('flow_packets_per_sec', models.FloatField(default=0)),
                ('fwd_packets_per_sec', models.FloatField(default=0)),
                ('bwd_packets_per_sec', models.FloatField(default=0)),
                ('flow_iat_mean', models.FloatField(default=0)),
                ('flow_iat_std', models.FloatField(default=0)),
                ('flow_iat_min', models.FloatField(default=0)),
                ('flow_iat_max', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_label', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField(default=0)),
                ('model_version', models.CharField(default='v1.0', max_length=30)),
                ('prediction_time', models.DateTimeField(auto_now_add=True)),
                ('packet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prediction', to='netpulse.networkpacket')),
            ],
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window_max_packet', to='netpulse.networkpacket')),
                ('min_packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window_min_packet', to='netpulse.networkpacket')),
            ],
        ),
        migrations.CreateModel(
            name='HuffmanStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_code_length', models.FloatField(default=0)),
                ('compression_rate', models.FloatField(default=0)),
                ('entropy_value', models.FloatField(default=0)),
                ('redundancy', models.FloatField(default=0)),
                ('window', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='huffman_stat', to='netpulse.window')),
            ],
        ),
        migrations.CreateModel(
            name='EntropyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entropy_value', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attack_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='netpulse.attacktype')),
                ('window', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='entropy_values', to='netpulse.window')),
            ],
        ),
    ]
