# Generated by Django 5.2.3 on 2025-06-18 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netpulse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkpacket',
            name='label',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='aiprediction',
            name='packet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_prediction', to='netpulse.networkpacket'),
        ),
    ]
